//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "user")] pub struct Model { # [sea_orm (primary_key)] pub id : i32 , pub name : String , # [sea_orm (unique)] pub email : String , pub password : String , # [sea_orm (unique)] pub uuid : Uuid , pub created_at : DateTime , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }